// Generated by Wrangler by running `wrangler types`

interface Env {
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_DATABASE_ID: string;
	CLOUDFLARE_D1_TOKEN: string;
	DB: D1Database;
	VEC_MODES: VectorizeIndex;
	VEC_TAGS: VectorizeIndex;
	AI: Ai;
}
